# Generated by Django 3.1.3 on 2021-03-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saverapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='Submitted', max_length=15),
            preserve_default=False,
        ),
    ]
