# Generated by Django 3.1.3 on 2021-03-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saverapp', '0003_auto_20210329_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Action Taken', 'Action Taken')], max_length=15),
        ),
    ]
